name: CI

on:
  push:
    branches: [ ft-chore/#182215531-integrate-coveralls-code-coverage-service ]
  pull_request:
    branches: [ ft-chore/#182215531-integrate-coveralls-code-coverage-service ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm i

    - name: Run tests
      run: npm run coverage
    
    - name: "Upload coverage report"
      run: |
       ci_env=`curl -s https://codecov.io/env`
       npm install codecov -g
       codecov -t 22a7c864-7bfc-4231-8af4-da32963eb6c1
